# Generated by Django 5.2.4 on 2025-08-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaillapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vaillapp.message'),
        ),
    ]
